### ISSUE TITLE
Actions seem to be broke

### ISSUE THREAD

**Issue by jbronikowski** [arraylabs/pymyq#51] opened 2020-10-26 03:38 UTC
Checking via Postman as a PUT and receiving the following for 

{
    "Message": "The requested resource does not support http method 'GET'."
}

Here is the payload

url = "http://api.myqdevice.com/api/v5.1/Accounts/XXXXXX/Devices/XXXXXXX/actions"

payload = "{\n    \"action_type\": \"close\"\n}"
headers = {
  'Content-Type': 'application/json',
  'MyQApplicationId': 'JVM/G9Nwih5BwKgNCjLxiFUQxQijAebyyg8QUHr7JOrP+tuPb8iHfRHKwTmDzHOu',
  'ApiVersion': '5.1',
  'BrandId': '2',
  'Culture': 'en',
  'SecurityToken': 'xxxxxxxx-xxxxxx-xxxxxxx'
}

**Comment by kyotodesertfox** [comment] 2020-10-27 14:30
Would this explain why as of this morning - HA shows it "Connected"; but the cover does not respond to Open / Close commands?

Side Question: Is there a replacement solution for MyQ? The frequency at which it (API) breaks / changes is becoming unreliable / untrustworthy for a smart home solution.

I definitely know that this is NOT a problem with Home Assistant; rather MyQ API constantly changing around on us.

**Comment by ehendrix23** [comment] 2020-10-27 16:44
I just ran example.py with the current pymyq version (2.0.8) and both my garage doors (I have 2) opened and then closed again without any issues.

**Comment by garyak** [comment] 2020-10-27 16:53
I see this behavior following a power transient. To restore function in HA requires a garage open/close cycle. A myQ hub reboot, or HA restart does not clear the problem for me. It's been this way for quite some time now.

**Comment by kyotodesertfox** [comment] 2020-10-27 16:57
> I see this behavior following a power transient

I did recently cut the power from the breaker a few days ago to install a new hallway light. The MyQ was on the same circuit when I killed power.

Are you suggesting this power cycle may have broke mine?

I do have a green light and I did attempt a power cycle of my MyQ device; but no change. 😭

**Comment by garyak** [comment] 2020-10-27 17:04
Yes. It's likely the power cycle was the root cause. Cycle the door and see if that clears your issue.

**Comment by ehendrix23** [comment] 2020-12-02 15:42
Closing as this seems an issue in the hub itself requiring a reboot and not an issue here.

**Closed as completed by ehendrix23** 2020-12-02 15:42 UTC
